fix type `list` support
shigma/minato pull request #18
Opened 2023-02-04 16:43 UTC by ifrvn

fix koishijs/console#83

2023-02-04 18:13 UTC, shigma requested changes
I'm very curious about how this PR will fix the dataview bug. Is there any explanation?

2023-02-04 18:13 UTC, shigma commented on packages/sql-utils/src/index.ts
> +      conditions.push(this.createEqualQuery(key, query.join(',')))
The changes here do not match the expected behavior. Is it the original code that caused the issue?

2023-02-04 18:13 UTC, shigma commented on packages/sql-utils/src/index.ts
> +        conditions.push(this.createMemberQuery(escapeId(key), query[key]))
`escapeId(key)` will become `'$in'`.

2023-02-05 00:47 UTC, ifrvn commented
重新捋了下，确实不是这么改 >_<

2023-02-05 01:03 UTC, ifrvn commented
主要是 list `["foo", "bar"]` 在 sqlite 里是 TEXT `foo,bar` ，用 `'key' in ('foo')` 是查不出数据的

如果 list 是空数组，select 的时候 createMemberQuery 会直接 return '0'，连SQL语句都不会生成

如果是null， `dump: value => value.join(',')` 也会炸

还是梦梦来修吧...

2023-02-05 02:41 UTC, ifrvn commented
![image](https://user-images.githubusercontent.com/21982381/216798728-36e2a144-e930-4195-8009-830b05e37c4d.png)

不会修了，`$in` 根本没转成SQL语句

2023-02-05 05:40 UTC, shigma approved these changes

2023-02-05 05:40 UTC, merged