feat: runtimeType, $.object, $.array
shigma/minato pull request #43
Opened 2023-10-26 06:40 UTC by Hieuzest

TODO but not planned now:
-	refactor runtimeType
-	rename $.object
-	impl sugar $.object(row)

Issues:
-	[maria 10.5 bug](https://jira.mariadb.org/browse/MDEV-26506)

2023-11-05 06:56 UTC, Hieuzest commented
PTAL @shigma

2023-11-09 11:54 UTC, shigma requested changes

2023-11-09 11:54 UTC, shigma commented on packages/core/src/eval.ts
> +    min<A extends boolean>(value: (Number | Expr<Number, A>)[] | Expr<Number[], A>): Expr<number, A>
```suggestion
    sum<A extends boolean>(value: (number | Expr<number, A>)[] | Expr<number[], A>): Expr<number, A>
    avg<A extends boolean>(value: (number | Expr<number, A>)[] | Expr<number[], A>): Expr<number, A>
    max<A extends boolean>(value: (number | Expr<number, A>)[] | Expr<number[], A>): Expr<number, A>
    min<A extends boolean>(value: (number | Expr<number, A>)[] | Expr<number[], A>): Expr<number, A>
    size<A extends boolean>(value: (Any | Expr<Any, A>)[] | Expr<Any[], A>): Expr<number, A>
```

2023-11-09 11:57 UTC, shigma commented on packages/core/src/eval.ts
> +    length<A extends boolean>(value: (Any | Expr<Any, A>)[] | Expr<Any[], A>): Expr<number, A>
```suggestion
    length<A extends boolean>(value: any[] | Expr<any[], A>): Expr<number, A>
```

2023-11-09 16:21 UTC, merged