feat(sqlite): update sql.js to 3.0.0
shigma/minato pull request #45
Opened 2023-11-11 19:33 UTC by shigma

cc @anillc

2023-11-12 03:47 UTC, Anillc requested changes

2023-11-12 03:47 UTC, Anillc commented on packages/sqlite/src/index.ts
> +    this.db = new this.SQLite.Database(undefined, buffer)
这里不应该传 `undefined` 呀，一定要传一个**绝对路径**，并且除了初始化，传了路径之后就不要传 `buffer` 了，@minatojs/sql.js 现在可以自己读文件了

2023-11-12 03:49 UTC, Anillc commented
怎么不能在 unchanged 的地方加 comment

stats 里应该直接用 fs api 读文件来获取大小（浏览器里还是 export）。一旦使用 `export` 就会导致之前一样的 bug, 所以无论如何都不应该把数据库拉到内存里。

2023-11-13 17:45 UTC, shigma commented
superseded by #47

2023-11-13 17:45 UTC, closed without merging